#!/bin/bash

# This script copies the Makefile file into a given directory and runs it.
# It's pretty dumb, but it was convenient to me.

# USAGE:
#   $ runFilter DIR

# Where:
#   DIR is the directory with the video files

cp Makefile $1

make -C $1

